# Generated by Django 4.2.4 on 2023-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwtIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
            ],
        ),
    ]
