# Generated by Django 4.2.4 on 2023-11-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0008_remove_profile_phone_number_profile_premium_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="code",
            field=models.CharField(default="abc", max_length=255),
            preserve_default=False,
        ),
    ]
