# Generated by Django 4.2.4 on 2023-11-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0009_voucher_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="voucherredeem",
            constraint=models.UniqueConstraint(
                fields=("user", "voucher"), name="user_voucher"
            ),
        ),
    ]
